### PR TITLE
Attempt xtensor update

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Testing that all works with latest xtensor 0.18.1 & xtensor-python 0.20

### CODE REVIEW

**Comment by constantinpape** [comment]
Ok, this seems to work.
Nevermind the appveyor tests, they are not working right now; I will need to check upon that at some point.

I will update the conda forge recipe accordingly.

**Comment by jakirkham** [comment]
This error seems different from the old AppVeyor errors.

```
c:\xtensor-conda\library\include\xtensor\xmath.hpp(273): error C2039: 'copysign': is not a member of 'std'
c:\xtensor-conda\library\include\xtl\xvariant_impl.hpp(2396): note: see declaration of 'std'
c:\xtensor-conda\library\include\xtensor\xmath.hpp(273): error C2873: 'copysign': symbol cannot be used in a using-declaration
```

ref: https://ci.appveyor.com/project/constantinpape/z5/builds/19609924/job/4m77l97gquhry1lj#L185
